name: Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: version-changed
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LAST_VERSION=${LAST_TAG#v}
          CURRENT_VERSION="${{ steps.package-version.outputs.version }}"

          if [ "$LAST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "⚠️ Version unchanged ($CURRENT_VERSION) - skipping release"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "✓ Version changed: $LAST_VERSION → $CURRENT_VERSION"
          fi

      - name: Determine version tag
        id: version-tag
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=v${{ steps.package-version.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Create git tag
        if: steps.version-changed.outputs.changed == 'true' && github.ref_type != 'tag'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.version-tag.outputs.tag }}" -m "Release ${{ steps.version-tag.outputs.tag }}"
          git push origin "${{ steps.version-tag.outputs.tag }}"

      - name: Generate professional changelog
        if: steps.version-changed.outputs.changed == 'true'
        id: changelog
        run: |
          # Generate changelog using conventional-changelog
          npx conventional-changelog -p angular -r 1 -o CHANGELOG_TEMP.md

          # Capture changelog content for GitHub Release
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG_TEMP.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Also update the CHANGELOG.md file for the repository
          if [ -f CHANGELOG.md ]; then
            npx conventional-changelog -p angular -i CHANGELOG.md -s
          else
            npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          fi

      - name: Create GitHub Release
        if: steps.version-changed.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version-tag.outputs.tag }}
          release_name: Release ${{ steps.version-tag.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false

      - name: Publish to npm
        if: steps.version-changed.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}